# ~/.zsh.d/starship.toml

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

# Use custom format
format = "[┌─ ](bold green)$all"

[character]
success_symbol = "[└─>](bold green) "
error_symbol = "[└─>[✗](bold red)](bold green) "
